name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: cargo build

      - name: Build with export feature
        run: cargo build --features export

      - name: Run tests
        run: cargo test

      - name: Run format check
        run: cargo fmt --check